### ISSUE TITLE
Convert local db to cloud db

### ISSUE THREAD

**Issue by Divide-By-0** [zkemail/relayer#21]
Right now we use a local db, which makes testing a bit harder and we are dependent on a single machine. Add a cloud DB instead to prevent things like double-emailing, and make it easier to switch between dev and prod deployments.

**Comment by curryrasul** [comment]
This is done in [Email Wallet](https://github.com/zkemail/email-wallet/tree/feat/v1) - changed the db from sqlite to postgres; should move db configuration to a separate file, but other than that it's done. 
Gonna close this issue
